### ISSUE TITLE
'load_pointcloud_from_h5' Attribute not found

### ISSUE THREAD

**Issue by naseem-amjad** [concept-fusion/concept-fusion#1]
Hi,

I am using Windows 10 with Python 3.9.16 with pip 23.0.1 , Installed Open3D , Torch (CPU) and GradSlam

Code sections are as following:

from gradslam.structures.pointclouds import Pointclouds

if __name__ == "__main__":

    # o3d.visualization.webrtc_server.enable_webrtc()

    # Process command-line args (if any)
    args = tyro.cli(ProgramArgs)

    pointclouds = Pointclouds.load_pointcloud_from_h5(args.load_path)#this line showing error
    pointclouds.to(args.device)

    print(f"Map embeddings: {pointclouds.embeddings_padded.shape}")

I am getting following error on issuing following command: python demo_click_query.py --load-path saved-map

\concept-fusion\examples\demo_click_query.py", line 81, in <module>
    pointclouds = Pointclouds.load_pointcloud_from_h5(args.load_path)
AttributeError: type object 'Pointclouds' has no attribute 'load_pointcloud_from_h5'

Kindly suggest what am I missing ? How can this problem be resolved?

**Comment by krrish94** [comment]
Hi @naseem-amjad, it appears that you could be using the main branch (or they pypi package) of gradslam, which do not have the `load_pointcloud_from_h5` functions (and a number of others, that are necessary for ConceptFusion).

I would recommend uninstalling all previous versions of `gradslam`, and then cloning the gradslam GitHub repo and building the `conceptfusion` branch from source.

```
git clone https://github.com/gradslam/gradslam.git
cd gradslam
git checkout conceptfusion
pip install -e .
```

Closing this for now, but feel free to reopen if the issue persists.

**Comment by krrish94** [comment]
Aside: running conceptfusion on a CPU-only machine might be infeasible (easily runs into OOM errors)
